version: '3'

tasks:
  dev:
    desc: Run the Judge UI development server with hot reload
    cmd: uv run uvicorn asciibench.judge_ui.main:app --reload

  test:
    desc: Run tests with pytest
    cmd: uv run pytest

  test-cov:
    desc: Run tests with coverage
    cmd: uv run pytest --cov=asciibench --cov-report=term-missing

  lint:
    desc: Run ruff linter
    cmd: uv run ruff check .

  lint-fix:
    desc: Run ruff linter with auto-fix
    cmd: uv run ruff check . --fix

  format:
    desc: Format code with ruff
    cmd: uv run ruff format .

  format-check:
    desc: Check code formatting without making changes
    cmd: uv run ruff format . --check

  typecheck:
    desc: Run type checking with ty
    cmd: uv run ty check

  check:
    desc: Run all checks (lint, format-check, typecheck, test)
    cmds:
      - task: lint
      - task: format-check
      - task: typecheck
      - task: test

  generate:
    desc: Generate ASCII art samples for all models
    cmd: uv run python -m asciibench.generator.main

  demo:
    desc: Run demo generator to create skeleton ASCII art from all models
    cmd: uv run python -m asciibench.generator.demo
