version: '3'

tasks:
  css:
    desc: Build Tailwind CSS
    cmd: npx tailwindcss -i ./input.css -o ./static/css/output.css --minify

  dev:
    desc: Build CSS and run the Judge UI development server with hot reload
    cmds:
      - task: css
      - uv run uvicorn asciibench.judge_ui.main:app --reload

  test:
    desc: Run tests with pytest
    cmd: uv run pytest

  check:
    desc: Run all checks (lint, format, typecheck, test)
    cmds:
      - uv run ruff check .
      - uv run ruff format . --check
      - uv run ty check
      - task: test

  generate:
    desc: Generate ASCII art samples for all models
    cmd: uv run python -m asciibench.generator.main

  demo:
    desc: Run demo generator to create skeleton ASCII art from all models
    cmd: uv run python -m asciibench.generator.demo

  evaluate:
    desc: Run VLM evaluator on ASCII art samples
    cmd: uv run python -m asciibench.evaluator.main
